apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: mongodb
  annotations:
    skip-initial-checks: "true"
spec:
  componentName: mongodb
  application: mongo-pacman-two-container
  containerImage: quay.io/jduimovich0/mongoserver:2023-03-04-165623
  targetPort: 27017
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
