apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pacman
  annotations:
    skip-initial-checks: "true"
spec:
  componentName: pacman
  application: mongo-pacman-two-container
  containerImage: quay.io/jduimovich0/pacman:2023-03-04-165623
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
