apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: jduimovich-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mongodb
    spec:
      containers:
        - image: quay.io/jduimovich0/mongoserver:2023-03-04-123157
          imagePullPolicy: Always
          name: container-image
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:  
  name: mongodb
  namespace: jduimovich-tenant
spec:
  ports:
  - port: 27017
    targetPort: 27017 
  selector:
    app.kubernetes.io/instance: mongodb
 